Models/ErrorViewModel.cs
namespace belajarASPDB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/NamaSiswaModel.cs
namespace belajarASPDB.Models
{
    public class NamaSiswaModel
    {
        public int id { get; set; }
        public string nama { get; set; }
        public string alamat { get; set; }

        public int usia { get; set; }

        public NamaSiswaModel()
        {

        }
    }
}

Controllers/HomeController.cs
using belajarASPDB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace belajarASPDB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/NamaSiswaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using belajarASPDB.Data;
using belajarASPDB.Models;
using Microsoft.AspNetCore.Authorization;

namespace belajarASPDB.Controllers
{
    public class NamaSiswaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NamaSiswaController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: NamaSiswa
        [Authorize]
        public async Task<IActionResult> Index()
        {

            return _context.NamaSiswaModel != null ?
                View(await _context.NamaSiswaModel.ToListAsync()) :
                Problem("Entity set ApplicationDbContext.NamaSiswaModel' is null. ");
        }

        // GET: NamaSiswa/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var namaSiswaModel = await _context.NamaSiswaModel
                .FirstOrDefaultAsync(m => m.id == id);
            if (namaSiswaModel == null)
            {
                return NotFound();
            }

            return View(namaSiswaModel);
        }

        // GET: NamaSiswa/Create

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: NamaSiswa/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nama,alamat,usia")] NamaSiswaModel namaSiswaModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(namaSiswaModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(namaSiswaModel);
        }

        // GET: NamaSiswa/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var namaSiswaModel = await _context.NamaSiswaModel.FindAsync(id);
            if (namaSiswaModel == null)
            {
                return NotFound();
            }
            return View(namaSiswaModel);
        }

        // POST: NamaSiswa/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nama,alamat,usia")] NamaSiswaModel namaSiswaModel)
        {
            if (id != namaSiswaModel.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(namaSiswaModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NamaSiswaModelExists(namaSiswaModel.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(namaSiswaModel);
        }

        // GET: NamaSiswa/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var namaSiswaModel = await _context.NamaSiswaModel
                .FirstOrDefaultAsync(m => m.id == id);
            if (namaSiswaModel == null)
            {
                return NotFound();
            }

            return View(namaSiswaModel);
        }

        // POST: NamaSiswa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var namaSiswaModel = await _context.NamaSiswaModel.FindAsync(id);
            if (namaSiswaModel != null)
            {
                _context.NamaSiswaModel.Remove(namaSiswaModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Cari()
        {
            return View();
        }

        public async Task<IActionResult> HasilPencarian(String KataKunci)
        {
            return View("Index", await _context.NamaSiswaModel.Where(j => j.nama.Contains(KataKunci)).ToListAsync());
        }

        private bool NamaSiswaModelExists(int id)
        {
            return _context.NamaSiswaModel.Any(e => e.id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/NamaSiswa/Cari.cshtml
<h4>NamaSiswaModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="HasilPencarian">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="KataKunci" class="control-label">Ketik Nama : </label>
                <input name="KataKunci" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Cari" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/NamaSiswa/Create.cshtml
@model belajarASPDB.Models.NamaSiswaModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>NamaSiswaModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nama" class="control-label"></label>
                <input asp-for="nama" class="form-control" />
                <span asp-validation-for="nama" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="alamat" class="control-label"></label>
                <input asp-for="alamat" class="form-control" />
                <span asp-validation-for="alamat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="usia" class="control-label"></label>
                <input asp-for="usia" class="form-control" />
                <span asp-validation-for="usia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/NamaSiswa/Delete.cshtml
@model belajarASPDB.Models.NamaSiswaModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NamaSiswaModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nama)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nama)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.alamat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.alamat)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/NamaSiswa/Details.cshtml
@model belajarASPDB.Models.NamaSiswaModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>NamaSiswaModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nama)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nama)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.alamat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.alamat)
        </dd>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.usia)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/NamaSiswa/Edit.cshtml
@model belajarASPDB.Models.NamaSiswaModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>NamaSiswaModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="nama" class="control-label"></label>
                <input asp-for="nama" class="form-control" />
                <span asp-validation-for="nama" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="alamat" class="control-label"></label>
                <input asp-for="alamat" class="form-control" />
                <span asp-validation-for="alamat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="usia" class="control-label"></label>
                <input asp-for="usia" class="form-control" />
                <span asp-validation-for="usia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/NamaSiswa/Index.cshtml
@model IEnumerable<belajarASPDB.Models.NamaSiswaModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nama)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.alamat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.usia)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nama)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.alamat)
            </td>
            <td>
                 @Html.DisplayFor(modelItem => item.usia)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - belajarASPDB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/belajarASPDB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">belajarASPDB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NamaSiswa" asp-action="Index">Data Siswa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NamaSiswa" asp-action="Cari">Cari Siswa</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - belajarASPDB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>